/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiDataRouteImport } from './routes/ai-data'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAccountsRouteImport } from './routes/app.accounts'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppAgentRouteImport } from './routes/app.agent'
import { Route as AppAgentSettingsRouteImport } from './routes/app.agent-settings'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAutomationsRouteImport } from './routes/app.automations'
import { Route as AppContextRouteImport } from './routes/app.context'
import { Route as AppDirectionRouteImport } from './routes/app.direction'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppIntegrityRouteImport } from './routes/app.integrity'
import { Route as AppMeRouteImport } from './routes/app.me'
import { Route as AppMoneyMapRouteImport } from './routes/app.money-map'
import { Route as AppNotificationSettingsRouteImport } from './routes/app.notification-settings'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppPersonalizationRouteImport } from './routes/app.personalization'
import { Route as AppPlanRouteImport } from './routes/app.plan'
import { Route as AppPlansRouteImport } from './routes/app.plans'
import { Route as AppPrivacyRouteImport } from './routes/app.privacy'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppProtectedRouteImport } from './routes/app.protected'
import { Route as AppRecurringRouteImport } from './routes/app.recurring'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppReviewRouteImport } from './routes/app.review'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppStrategyRouteImport } from './routes/app.strategy'
import { Route as AppTransactionsRouteImport } from './routes/app.transactions'
import { Route as AppWalletsRouteImport } from './routes/app.wallets'
import { Route as AppAccountsIndexRouteImport } from './routes/app.accounts.index'
import { Route as AppAccountsAccountIdRouteImport } from './routes/app.accounts.$accountId'
import { Route as AppAgentIndexRouteImport } from './routes/app.agent.index'
import { Route as AppAgentConversationIdRouteImport } from './routes/app.agent.$conversationId'
import { Route as AppAnalyticsIndexRouteImport } from './routes/app.analytics.index'
import { Route as AppGoalsIndexRouteImport } from './routes/app.goals.index'
import { Route as AppGoalsGoalIdRouteImport } from './routes/app.goals.$goalId'
import { Route as AppPlansIndexRouteImport } from './routes/app.plans.index'
import { Route as AppPlansPlanIdRouteImport } from './routes/app.plans.$planId'
import { Route as AppProfileIndexRouteImport } from './routes/app.profile.index'
import { Route as AppProfileMethodsRouteImport } from './routes/app.profile.methods'
import { Route as AppProfilePasswordRouteImport } from './routes/app.profile.password'
import { Route as AppProfilePersonalRouteImport } from './routes/app.profile.personal'
import { Route as AppProfileSecurityRouteImport } from './routes/app.profile.security'
import { Route as AppWalletsIndexRouteImport } from './routes/app.wallets.index'
import { Route as AppWalletsWalletIdRouteImport } from './routes/app.wallets.$walletId'
import { Route as AppAnalyticsCategoryCategoryIdRouteImport } from './routes/app.analytics.category.$categoryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDataRoute = AiDataRouteImport.update({
  id: '/ai-data',
  path: '/ai-data',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentSettingsRoute = AppAgentSettingsRouteImport.update({
  id: '/agent-settings',
  path: '/agent-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppContextRoute = AppContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectionRoute = AppDirectionRouteImport.update({
  id: '/direction',
  path: '/direction',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrityRoute = AppIntegrityRouteImport.update({
  id: '/integrity',
  path: '/integrity',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyMapRoute = AppMoneyMapRouteImport.update({
  id: '/money-map',
  path: '/money-map',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationSettingsRoute = AppNotificationSettingsRouteImport.update({
  id: '/notification-settings',
  path: '/notification-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonalizationRoute = AppPersonalizationRouteImport.update({
  id: '/personalization',
  path: '/personalization',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProtectedRoute = AppProtectedRouteImport.update({
  id: '/protected',
  path: '/protected',
  getParentRoute: () => AppRoute,
} as any)
const AppRecurringRoute = AppRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStrategyRoute = AppStrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletsRoute = AppWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppAccountsAccountIdRoute = AppAccountsAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppAgentIndexRoute = AppAgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAgentRoute,
} as any)
const AppAgentConversationIdRoute = AppAgentConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => AppAgentRoute,
} as any)
const AppAnalyticsIndexRoute = AppAnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAnalyticsRoute,
} as any)
const AppGoalsIndexRoute = AppGoalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGoalsRoute,
} as any)
const AppGoalsGoalIdRoute = AppGoalsGoalIdRouteImport.update({
  id: '/$goalId',
  path: '/$goalId',
  getParentRoute: () => AppGoalsRoute,
} as any)
const AppPlansIndexRoute = AppPlansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPlansRoute,
} as any)
const AppPlansPlanIdRoute = AppPlansPlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => AppPlansRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfileMethodsRoute = AppProfileMethodsRouteImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfilePasswordRoute = AppProfilePasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfilePersonalRoute = AppProfilePersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfileSecurityRoute = AppProfileSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppWalletsIndexRoute = AppWalletsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWalletsRoute,
} as any)
const AppWalletsWalletIdRoute = AppWalletsWalletIdRouteImport.update({
  id: '/$walletId',
  path: '/$walletId',
  getParentRoute: () => AppWalletsRoute,
} as any)
const AppAnalyticsCategoryCategoryIdRoute =
  AppAnalyticsCategoryCategoryIdRouteImport.update({
    id: '/category/$categoryId',
    path: '/category/$categoryId',
    getParentRoute: () => AppAnalyticsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-data': typeof AiDataRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/app/accounts': typeof AppAccountsRouteWithChildren
  '/app/activity': typeof AppActivityRoute
  '/app/agent': typeof AppAgentRouteWithChildren
  '/app/agent-settings': typeof AppAgentSettingsRoute
  '/app/analytics': typeof AppAnalyticsRouteWithChildren
  '/app/automations': typeof AppAutomationsRoute
  '/app/context': typeof AppContextRoute
  '/app/direction': typeof AppDirectionRoute
  '/app/goals': typeof AppGoalsRouteWithChildren
  '/app/help': typeof AppHelpRoute
  '/app/integrity': typeof AppIntegrityRoute
  '/app/me': typeof AppMeRoute
  '/app/money-map': typeof AppMoneyMapRoute
  '/app/notification-settings': typeof AppNotificationSettingsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/personalization': typeof AppPersonalizationRoute
  '/app/plan': typeof AppPlanRoute
  '/app/plans': typeof AppPlansRouteWithChildren
  '/app/privacy': typeof AppPrivacyRoute
  '/app/profile': typeof AppProfileRouteWithChildren
  '/app/protected': typeof AppProtectedRoute
  '/app/recurring': typeof AppRecurringRoute
  '/app/reports': typeof AppReportsRoute
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/strategy': typeof AppStrategyRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/wallets': typeof AppWalletsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/app/agent/$conversationId': typeof AppAgentConversationIdRoute
  '/app/goals/$goalId': typeof AppGoalsGoalIdRoute
  '/app/plans/$planId': typeof AppPlansPlanIdRoute
  '/app/profile/methods': typeof AppProfileMethodsRoute
  '/app/profile/password': typeof AppProfilePasswordRoute
  '/app/profile/personal': typeof AppProfilePersonalRoute
  '/app/profile/security': typeof AppProfileSecurityRoute
  '/app/wallets/$walletId': typeof AppWalletsWalletIdRoute
  '/app/accounts/': typeof AppAccountsIndexRoute
  '/app/agent/': typeof AppAgentIndexRoute
  '/app/analytics/': typeof AppAnalyticsIndexRoute
  '/app/goals/': typeof AppGoalsIndexRoute
  '/app/plans/': typeof AppPlansIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/wallets/': typeof AppWalletsIndexRoute
  '/app/analytics/category/$categoryId': typeof AppAnalyticsCategoryCategoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-data': typeof AiDataRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/agent-settings': typeof AppAgentSettingsRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/context': typeof AppContextRoute
  '/app/direction': typeof AppDirectionRoute
  '/app/help': typeof AppHelpRoute
  '/app/integrity': typeof AppIntegrityRoute
  '/app/me': typeof AppMeRoute
  '/app/money-map': typeof AppMoneyMapRoute
  '/app/notification-settings': typeof AppNotificationSettingsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/personalization': typeof AppPersonalizationRoute
  '/app/plan': typeof AppPlanRoute
  '/app/privacy': typeof AppPrivacyRoute
  '/app/protected': typeof AppProtectedRoute
  '/app/recurring': typeof AppRecurringRoute
  '/app/reports': typeof AppReportsRoute
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/strategy': typeof AppStrategyRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app': typeof AppIndexRoute
  '/app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/app/agent/$conversationId': typeof AppAgentConversationIdRoute
  '/app/goals/$goalId': typeof AppGoalsGoalIdRoute
  '/app/plans/$planId': typeof AppPlansPlanIdRoute
  '/app/profile/methods': typeof AppProfileMethodsRoute
  '/app/profile/password': typeof AppProfilePasswordRoute
  '/app/profile/personal': typeof AppProfilePersonalRoute
  '/app/profile/security': typeof AppProfileSecurityRoute
  '/app/wallets/$walletId': typeof AppWalletsWalletIdRoute
  '/app/accounts': typeof AppAccountsIndexRoute
  '/app/agent': typeof AppAgentIndexRoute
  '/app/analytics': typeof AppAnalyticsIndexRoute
  '/app/goals': typeof AppGoalsIndexRoute
  '/app/plans': typeof AppPlansIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/wallets': typeof AppWalletsIndexRoute
  '/app/analytics/category/$categoryId': typeof AppAnalyticsCategoryCategoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-data': typeof AiDataRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/app/accounts': typeof AppAccountsRouteWithChildren
  '/app/activity': typeof AppActivityRoute
  '/app/agent': typeof AppAgentRouteWithChildren
  '/app/agent-settings': typeof AppAgentSettingsRoute
  '/app/analytics': typeof AppAnalyticsRouteWithChildren
  '/app/automations': typeof AppAutomationsRoute
  '/app/context': typeof AppContextRoute
  '/app/direction': typeof AppDirectionRoute
  '/app/goals': typeof AppGoalsRouteWithChildren
  '/app/help': typeof AppHelpRoute
  '/app/integrity': typeof AppIntegrityRoute
  '/app/me': typeof AppMeRoute
  '/app/money-map': typeof AppMoneyMapRoute
  '/app/notification-settings': typeof AppNotificationSettingsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/personalization': typeof AppPersonalizationRoute
  '/app/plan': typeof AppPlanRoute
  '/app/plans': typeof AppPlansRouteWithChildren
  '/app/privacy': typeof AppPrivacyRoute
  '/app/profile': typeof AppProfileRouteWithChildren
  '/app/protected': typeof AppProtectedRoute
  '/app/recurring': typeof AppRecurringRoute
  '/app/reports': typeof AppReportsRoute
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/strategy': typeof AppStrategyRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/wallets': typeof AppWalletsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/app/agent/$conversationId': typeof AppAgentConversationIdRoute
  '/app/goals/$goalId': typeof AppGoalsGoalIdRoute
  '/app/plans/$planId': typeof AppPlansPlanIdRoute
  '/app/profile/methods': typeof AppProfileMethodsRoute
  '/app/profile/password': typeof AppProfilePasswordRoute
  '/app/profile/personal': typeof AppProfilePersonalRoute
  '/app/profile/security': typeof AppProfileSecurityRoute
  '/app/wallets/$walletId': typeof AppWalletsWalletIdRoute
  '/app/accounts/': typeof AppAccountsIndexRoute
  '/app/agent/': typeof AppAgentIndexRoute
  '/app/analytics/': typeof AppAnalyticsIndexRoute
  '/app/goals/': typeof AppGoalsIndexRoute
  '/app/plans/': typeof AppPlansIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/wallets/': typeof AppWalletsIndexRoute
  '/app/analytics/category/$categoryId': typeof AppAnalyticsCategoryCategoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-data'
    | '/app'
    | '/auth'
    | '/forgot-password'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/app/accounts'
    | '/app/activity'
    | '/app/agent'
    | '/app/agent-settings'
    | '/app/analytics'
    | '/app/automations'
    | '/app/context'
    | '/app/direction'
    | '/app/goals'
    | '/app/help'
    | '/app/integrity'
    | '/app/me'
    | '/app/money-map'
    | '/app/notification-settings'
    | '/app/notifications'
    | '/app/personalization'
    | '/app/plan'
    | '/app/plans'
    | '/app/privacy'
    | '/app/profile'
    | '/app/protected'
    | '/app/recurring'
    | '/app/reports'
    | '/app/review'
    | '/app/settings'
    | '/app/strategy'
    | '/app/transactions'
    | '/app/wallets'
    | '/app/'
    | '/app/accounts/$accountId'
    | '/app/agent/$conversationId'
    | '/app/goals/$goalId'
    | '/app/plans/$planId'
    | '/app/profile/methods'
    | '/app/profile/password'
    | '/app/profile/personal'
    | '/app/profile/security'
    | '/app/wallets/$walletId'
    | '/app/accounts/'
    | '/app/agent/'
    | '/app/analytics/'
    | '/app/goals/'
    | '/app/plans/'
    | '/app/profile/'
    | '/app/wallets/'
    | '/app/analytics/category/$categoryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-data'
    | '/auth'
    | '/forgot-password'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/app/activity'
    | '/app/agent-settings'
    | '/app/automations'
    | '/app/context'
    | '/app/direction'
    | '/app/help'
    | '/app/integrity'
    | '/app/me'
    | '/app/money-map'
    | '/app/notification-settings'
    | '/app/notifications'
    | '/app/personalization'
    | '/app/plan'
    | '/app/privacy'
    | '/app/protected'
    | '/app/recurring'
    | '/app/reports'
    | '/app/review'
    | '/app/settings'
    | '/app/strategy'
    | '/app/transactions'
    | '/app'
    | '/app/accounts/$accountId'
    | '/app/agent/$conversationId'
    | '/app/goals/$goalId'
    | '/app/plans/$planId'
    | '/app/profile/methods'
    | '/app/profile/password'
    | '/app/profile/personal'
    | '/app/profile/security'
    | '/app/wallets/$walletId'
    | '/app/accounts'
    | '/app/agent'
    | '/app/analytics'
    | '/app/goals'
    | '/app/plans'
    | '/app/profile'
    | '/app/wallets'
    | '/app/analytics/category/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/ai-data'
    | '/app'
    | '/auth'
    | '/forgot-password'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/app/accounts'
    | '/app/activity'
    | '/app/agent'
    | '/app/agent-settings'
    | '/app/analytics'
    | '/app/automations'
    | '/app/context'
    | '/app/direction'
    | '/app/goals'
    | '/app/help'
    | '/app/integrity'
    | '/app/me'
    | '/app/money-map'
    | '/app/notification-settings'
    | '/app/notifications'
    | '/app/personalization'
    | '/app/plan'
    | '/app/plans'
    | '/app/privacy'
    | '/app/profile'
    | '/app/protected'
    | '/app/recurring'
    | '/app/reports'
    | '/app/review'
    | '/app/settings'
    | '/app/strategy'
    | '/app/transactions'
    | '/app/wallets'
    | '/app/'
    | '/app/accounts/$accountId'
    | '/app/agent/$conversationId'
    | '/app/goals/$goalId'
    | '/app/plans/$planId'
    | '/app/profile/methods'
    | '/app/profile/password'
    | '/app/profile/personal'
    | '/app/profile/security'
    | '/app/wallets/$walletId'
    | '/app/accounts/'
    | '/app/agent/'
    | '/app/analytics/'
    | '/app/goals/'
    | '/app/plans/'
    | '/app/profile/'
    | '/app/wallets/'
    | '/app/analytics/category/$categoryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiDataRoute: typeof AiDataRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-data': {
      id: '/ai-data'
      path: '/ai-data'
      fullPath: '/ai-data'
      preLoaderRoute: typeof AiDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent': {
      id: '/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent-settings': {
      id: '/app/agent-settings'
      path: '/agent-settings'
      fullPath: '/app/agent-settings'
      preLoaderRoute: typeof AppAgentSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/automations': {
      id: '/app/automations'
      path: '/automations'
      fullPath: '/app/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/context': {
      id: '/app/context'
      path: '/context'
      fullPath: '/app/context'
      preLoaderRoute: typeof AppContextRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/direction': {
      id: '/app/direction'
      path: '/direction'
      fullPath: '/app/direction'
      preLoaderRoute: typeof AppDirectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrity': {
      id: '/app/integrity'
      path: '/integrity'
      fullPath: '/app/integrity'
      preLoaderRoute: typeof AppIntegrityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me': {
      id: '/app/me'
      path: '/me'
      fullPath: '/app/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/money-map': {
      id: '/app/money-map'
      path: '/money-map'
      fullPath: '/app/money-map'
      preLoaderRoute: typeof AppMoneyMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notification-settings': {
      id: '/app/notification-settings'
      path: '/notification-settings'
      fullPath: '/app/notification-settings'
      preLoaderRoute: typeof AppNotificationSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/personalization': {
      id: '/app/personalization'
      path: '/personalization'
      fullPath: '/app/personalization'
      preLoaderRoute: typeof AppPersonalizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plan': {
      id: '/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plans': {
      id: '/app/plans'
      path: '/plans'
      fullPath: '/app/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/privacy': {
      id: '/app/privacy'
      path: '/privacy'
      fullPath: '/app/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/protected': {
      id: '/app/protected'
      path: '/protected'
      fullPath: '/app/protected'
      preLoaderRoute: typeof AppProtectedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recurring': {
      id: '/app/recurring'
      path: '/recurring'
      fullPath: '/app/recurring'
      preLoaderRoute: typeof AppRecurringRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review': {
      id: '/app/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/strategy': {
      id: '/app/strategy'
      path: '/strategy'
      fullPath: '/app/strategy'
      preLoaderRoute: typeof AppStrategyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallets': {
      id: '/app/wallets'
      path: '/wallets'
      fullPath: '/app/wallets'
      preLoaderRoute: typeof AppWalletsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounts/': {
      id: '/app/accounts/'
      path: '/'
      fullPath: '/app/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/app/accounts/$accountId': {
      id: '/app/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/app/accounts/$accountId'
      preLoaderRoute: typeof AppAccountsAccountIdRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/app/agent/': {
      id: '/app/agent/'
      path: '/'
      fullPath: '/app/agent/'
      preLoaderRoute: typeof AppAgentIndexRouteImport
      parentRoute: typeof AppAgentRoute
    }
    '/app/agent/$conversationId': {
      id: '/app/agent/$conversationId'
      path: '/$conversationId'
      fullPath: '/app/agent/$conversationId'
      preLoaderRoute: typeof AppAgentConversationIdRouteImport
      parentRoute: typeof AppAgentRoute
    }
    '/app/analytics/': {
      id: '/app/analytics/'
      path: '/'
      fullPath: '/app/analytics/'
      preLoaderRoute: typeof AppAnalyticsIndexRouteImport
      parentRoute: typeof AppAnalyticsRoute
    }
    '/app/goals/': {
      id: '/app/goals/'
      path: '/'
      fullPath: '/app/goals/'
      preLoaderRoute: typeof AppGoalsIndexRouteImport
      parentRoute: typeof AppGoalsRoute
    }
    '/app/goals/$goalId': {
      id: '/app/goals/$goalId'
      path: '/$goalId'
      fullPath: '/app/goals/$goalId'
      preLoaderRoute: typeof AppGoalsGoalIdRouteImport
      parentRoute: typeof AppGoalsRoute
    }
    '/app/plans/': {
      id: '/app/plans/'
      path: '/'
      fullPath: '/app/plans/'
      preLoaderRoute: typeof AppPlansIndexRouteImport
      parentRoute: typeof AppPlansRoute
    }
    '/app/plans/$planId': {
      id: '/app/plans/$planId'
      path: '/$planId'
      fullPath: '/app/plans/$planId'
      preLoaderRoute: typeof AppPlansPlanIdRouteImport
      parentRoute: typeof AppPlansRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/app/profile/methods': {
      id: '/app/profile/methods'
      path: '/methods'
      fullPath: '/app/profile/methods'
      preLoaderRoute: typeof AppProfileMethodsRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/app/profile/password': {
      id: '/app/profile/password'
      path: '/password'
      fullPath: '/app/profile/password'
      preLoaderRoute: typeof AppProfilePasswordRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/app/profile/personal': {
      id: '/app/profile/personal'
      path: '/personal'
      fullPath: '/app/profile/personal'
      preLoaderRoute: typeof AppProfilePersonalRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/app/profile/security': {
      id: '/app/profile/security'
      path: '/security'
      fullPath: '/app/profile/security'
      preLoaderRoute: typeof AppProfileSecurityRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/app/wallets/': {
      id: '/app/wallets/'
      path: '/'
      fullPath: '/app/wallets/'
      preLoaderRoute: typeof AppWalletsIndexRouteImport
      parentRoute: typeof AppWalletsRoute
    }
    '/app/wallets/$walletId': {
      id: '/app/wallets/$walletId'
      path: '/$walletId'
      fullPath: '/app/wallets/$walletId'
      preLoaderRoute: typeof AppWalletsWalletIdRouteImport
      parentRoute: typeof AppWalletsRoute
    }
    '/app/analytics/category/$categoryId': {
      id: '/app/analytics/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/app/analytics/category/$categoryId'
      preLoaderRoute: typeof AppAnalyticsCategoryCategoryIdRouteImport
      parentRoute: typeof AppAnalyticsRoute
    }
  }
}

interface AppAccountsRouteChildren {
  AppAccountsAccountIdRoute: typeof AppAccountsAccountIdRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
}

const AppAccountsRouteChildren: AppAccountsRouteChildren = {
  AppAccountsAccountIdRoute: AppAccountsAccountIdRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
}

const AppAccountsRouteWithChildren = AppAccountsRoute._addFileChildren(
  AppAccountsRouteChildren,
)

interface AppAgentRouteChildren {
  AppAgentConversationIdRoute: typeof AppAgentConversationIdRoute
  AppAgentIndexRoute: typeof AppAgentIndexRoute
}

const AppAgentRouteChildren: AppAgentRouteChildren = {
  AppAgentConversationIdRoute: AppAgentConversationIdRoute,
  AppAgentIndexRoute: AppAgentIndexRoute,
}

const AppAgentRouteWithChildren = AppAgentRoute._addFileChildren(
  AppAgentRouteChildren,
)

interface AppAnalyticsRouteChildren {
  AppAnalyticsIndexRoute: typeof AppAnalyticsIndexRoute
  AppAnalyticsCategoryCategoryIdRoute: typeof AppAnalyticsCategoryCategoryIdRoute
}

const AppAnalyticsRouteChildren: AppAnalyticsRouteChildren = {
  AppAnalyticsIndexRoute: AppAnalyticsIndexRoute,
  AppAnalyticsCategoryCategoryIdRoute: AppAnalyticsCategoryCategoryIdRoute,
}

const AppAnalyticsRouteWithChildren = AppAnalyticsRoute._addFileChildren(
  AppAnalyticsRouteChildren,
)

interface AppGoalsRouteChildren {
  AppGoalsGoalIdRoute: typeof AppGoalsGoalIdRoute
  AppGoalsIndexRoute: typeof AppGoalsIndexRoute
}

const AppGoalsRouteChildren: AppGoalsRouteChildren = {
  AppGoalsGoalIdRoute: AppGoalsGoalIdRoute,
  AppGoalsIndexRoute: AppGoalsIndexRoute,
}

const AppGoalsRouteWithChildren = AppGoalsRoute._addFileChildren(
  AppGoalsRouteChildren,
)

interface AppPlansRouteChildren {
  AppPlansPlanIdRoute: typeof AppPlansPlanIdRoute
  AppPlansIndexRoute: typeof AppPlansIndexRoute
}

const AppPlansRouteChildren: AppPlansRouteChildren = {
  AppPlansPlanIdRoute: AppPlansPlanIdRoute,
  AppPlansIndexRoute: AppPlansIndexRoute,
}

const AppPlansRouteWithChildren = AppPlansRoute._addFileChildren(
  AppPlansRouteChildren,
)

interface AppProfileRouteChildren {
  AppProfileMethodsRoute: typeof AppProfileMethodsRoute
  AppProfilePasswordRoute: typeof AppProfilePasswordRoute
  AppProfilePersonalRoute: typeof AppProfilePersonalRoute
  AppProfileSecurityRoute: typeof AppProfileSecurityRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileMethodsRoute: AppProfileMethodsRoute,
  AppProfilePasswordRoute: AppProfilePasswordRoute,
  AppProfilePersonalRoute: AppProfilePersonalRoute,
  AppProfileSecurityRoute: AppProfileSecurityRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppWalletsRouteChildren {
  AppWalletsWalletIdRoute: typeof AppWalletsWalletIdRoute
  AppWalletsIndexRoute: typeof AppWalletsIndexRoute
}

const AppWalletsRouteChildren: AppWalletsRouteChildren = {
  AppWalletsWalletIdRoute: AppWalletsWalletIdRoute,
  AppWalletsIndexRoute: AppWalletsIndexRoute,
}

const AppWalletsRouteWithChildren = AppWalletsRoute._addFileChildren(
  AppWalletsRouteChildren,
)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRouteWithChildren
  AppActivityRoute: typeof AppActivityRoute
  AppAgentRoute: typeof AppAgentRouteWithChildren
  AppAgentSettingsRoute: typeof AppAgentSettingsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRouteWithChildren
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppContextRoute: typeof AppContextRoute
  AppDirectionRoute: typeof AppDirectionRoute
  AppGoalsRoute: typeof AppGoalsRouteWithChildren
  AppHelpRoute: typeof AppHelpRoute
  AppIntegrityRoute: typeof AppIntegrityRoute
  AppMeRoute: typeof AppMeRoute
  AppMoneyMapRoute: typeof AppMoneyMapRoute
  AppNotificationSettingsRoute: typeof AppNotificationSettingsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPersonalizationRoute: typeof AppPersonalizationRoute
  AppPlanRoute: typeof AppPlanRoute
  AppPlansRoute: typeof AppPlansRouteWithChildren
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppProtectedRoute: typeof AppProtectedRoute
  AppRecurringRoute: typeof AppRecurringRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStrategyRoute: typeof AppStrategyRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppWalletsRoute: typeof AppWalletsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRouteWithChildren,
  AppActivityRoute: AppActivityRoute,
  AppAgentRoute: AppAgentRouteWithChildren,
  AppAgentSettingsRoute: AppAgentSettingsRoute,
  AppAnalyticsRoute: AppAnalyticsRouteWithChildren,
  AppAutomationsRoute: AppAutomationsRoute,
  AppContextRoute: AppContextRoute,
  AppDirectionRoute: AppDirectionRoute,
  AppGoalsRoute: AppGoalsRouteWithChildren,
  AppHelpRoute: AppHelpRoute,
  AppIntegrityRoute: AppIntegrityRoute,
  AppMeRoute: AppMeRoute,
  AppMoneyMapRoute: AppMoneyMapRoute,
  AppNotificationSettingsRoute: AppNotificationSettingsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPersonalizationRoute: AppPersonalizationRoute,
  AppPlanRoute: AppPlanRoute,
  AppPlansRoute: AppPlansRouteWithChildren,
  AppPrivacyRoute: AppPrivacyRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppProtectedRoute: AppProtectedRoute,
  AppRecurringRoute: AppRecurringRoute,
  AppReportsRoute: AppReportsRoute,
  AppReviewRoute: AppReviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStrategyRoute: AppStrategyRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppWalletsRoute: AppWalletsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiDataRoute: AiDataRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
